services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"

  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  celery-worker:
    build: .
    container_name: celery_worker
    command: celery -A app.celery_app.celery worker --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
